### PR TITLE
remove references to azure

### LINKED ISSUE #5: Make the client more generic in terms of auth providers
Currently the client is set up specifically for auth through Azure AD. We want to make it easy to add support for different auth providers.

To enable this for future clients, change the property name `azure_credentials` on the client to something more generic - maybe `get_credentials`.

Also need to change the config variable names so that nothing named `azure` remains, and it is entirely generic.

### PR DESCRIPTION
**Pull request by gnieuwenhuis**
Closes #5 

In order tot keep the client more generic for future use cases, we will remove explicit references to Azure in variable and client property names

### CODE REVIEW

**Comment by michaelconnor00** [comment]
I may have confused the naming of the settings variables. I do think the variables should be prefixed with `PRESCIENT_`, for readability and so there is no chance of overwriting other variables. I just think the .env file and the env vars should use the same names.

**Comment by gnieuwenhuis** [comment]
I agree - my example above is consistent and makes the most sense I think .... I wouldn't like it much if using settings in the code like that was the main way to do it, but that's not the case

**Comment by michaelconnor00** [comment]
Makes sense to me. Thanks.

**Comment by gnieuwenhuis** [comment]
This should be done now @michaelconnor00 and ready for you to check again

**Review by michaelconnor00 — APPROVED** [review]
LGTM

**Pull request merged**
